language: ruby
rvm:
- 2.3.1
before_script:
- npm install -g bower
- bower install
- chmod +x ./deploy.sh
script: ./deploy.sh
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - COMMIT_AUTHOR_EMAIL: me@marcanuy.com
  - ENCRYPTION_LABEL: fa2f6748cce2
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_fa2f6748cce2_key -iv $encrypted_fa2f6748cce2_iv -in id_rsa.pub.enc -out deploy_key -d